name: Copy
on:
  workflow_dispatch:

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
    - name: Copycat
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        src_path: /.github/workflows
        src_branch: main
        dst_path: /.github/workflows
        dst_branch: main
        dst_owner: Tencent
        dst_repo_name: tdesign-react
        filter: '**/*.temp.yml'
        username: 94dreamer
        email: 503633021@qq.com
        commit_message: 'ci: update files "/.github/workflows" from "Tencent/tdesign"'