name: Copy
on:
  workflow_dispatch:

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
    - name: Copycat
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        src_path: /.
        src_branch: feature/action-report
        dst_branch: main
        dst_path: /.github/workflows
        dst_owner: 94dreamer
        dst_repo_name: test-action
        filter: '**/*.temp.yml'
        # exclude: */actions/*
        username: 94dreamer
        email: 503633021@qq.com