# 生成 github 情况
name: issues-day-statistics

on:
  workflow_call:

jobs:
  create-report:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/create-report
        with:
          wxhook: ${{ secrets.WX_HOOK_URL }}
          token: ${{ secrets.GIT_TOKEN_L }}
