# 国际标准时间+8
name: issues-dailyclose-schedule

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

jobs:
  create-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/create-report
        with:
          wxhook: ${{ secrets.WX_HOOK_URL }}
          token: ${{ secrets.GIT_TOKEN_L }}
          type: 'close'
