# 国际标准时间+8
name: issues-statistics-schedule

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"

jobs:
  call-statist:
    uses: Tencent/tdesign/.github/workflows/issues-statistics.yml@main
    secrets:
      WX_HOOK_URL: ${{ secrets.WX_HOOK_URL }}
      GIT_TOKEN_L: ${{ secrets.GIT_TOKEN_L }}
