# 生成 github 情况
name: issues-day-statistics

on:
  workflow_call:
    secrets:
      WX_HOOK_URL:
        required: true
      GIT_TOKEN_L:
        required: true

jobs:
  create-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/create-report
        with:
          wxhook: ${{ secrets.WX_HOOK_URL }}
          token: ${{ secrets.GIT_TOKEN_L }}
